# Auto-generated by generate_sources.cmake
set(runtime_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/dinput8.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/filesystem/blowfish.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/filesystem/msd.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/filesystem/resource.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/hooks/core_hooks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/hooks/hooks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/hooks/inventory_hooks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/hooks/resource_hooks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/hooks/shop_hooks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/memory/dataverify.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/modloader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/utilities/console.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/utilities/gui.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/utilities/logger.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/wolf_runtime_api.cpp
)
