name: Bug Report
description: Report a bug or issue with okami-apclient
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: A clear description of what the bug is
      render: text
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened instead?
      render: text
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: input
    id: wolf-version
    attributes:
      label: WOLF Version
      description: Version of WOLF
      placeholder: e.g., v1.2.3
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows 11
        - Windows 10
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: log-files
    attributes:
      label: Log Files
      description: Please paste or upload relevant log entries from the `logs/` directory
      placeholder: Paste relevant log entries here or upload your log file
    validations:
      required: true

  - type: checkboxes
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does this happen?
      options:
        - label: Happens every time
        - label: Happens sometimes
        - label: Happened once
        - label: Can't reproduce

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a way to work around this issue?
      placeholder: Describe any workarounds you've found
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem:
        - Screenshots/Videos (if applicable)
        - Save file information (does this happen with specific save files?)
        - Any other relevant information
      placeholder: Add any other context, screenshots, or information about the problem
