name: Feature Request
description: Suggest a new feature or enhancement for WOLF
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: A clear description of the feature you'd like
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Problem This Solves
      description: What problem does this solve?
      placeholder: Describe the problem or use case this feature addresses
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: Describe how this would fit into your gameplay or workflow
    validations:
      required: true

  - type: checkboxes
    id: beneficiaries
    attributes:
      label: Who would benefit from this?
      options:
        - label: End Users
        - label: Mod Devs
        - label: WOLF Devs / Maintainers

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas for how this could work?
      placeholder: any thoughts on implementation, UI/UX, etc.

  - type: textarea
    id: related-features
    attributes:
      label: Related Features
      description: Does this build on or modify existing functionality?
      placeholder: Describe any related existing features

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Similar features in other, similar modding frameworks
      placeholder: If you've seen this in other places

  - type: dropdown
    id: importance
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would improve my experience significantly
        - Essential for my use case
        - Blocking me from using the framework
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      options:
        - No rush
        - Would like it eventually
        - Needed soon
        - Urgent
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information about the feature request
      placeholder: Any other context or information
