# Auto-generated by generate_sources.cmake
set(devtools_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/devdatafinder.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/devtools.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/devtools_gui.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/gamestateregistry.cpp
)
