#pragma once

namespace okami
{
namespace BestiaryTome
{
enum Enum
{
    GreenImp,
    RedImp,
    YellowImp,
    BlueImp,
    BlackImp,
    HeadlessGuardian,
    BellGuardian,
    HaloGuardian,
    ExecutionerGuardian,
    Namahage,
    BladeNamahage,
    BucketNamahage,
    UmbrellaNamahage,
    CannonNamahage,
    ClaySoldier,
    ClaySamurai,
    ClayDrummer,
    ClayFlyer,
    ClayShogun,
    BudOgre,
    Chimera,
    IglooTurtle,
    DeadFish,
    CrowTengu,
    Ubume,
    FireEye,
    IceMouth,
    ThunderEar,
    EarthNose,
    FireDoomMirror,
    IceDoomMirror,
    ThunderDoomMirror,
    WindDoomMirror,
    Poltergeist,
    Ichiro,
    Jiro,
    Saburo,
    BlueCyclops,
    GreatTengu,
    CrimsonHelm,
    RedOgre,
    BlueOgre,
    BullCharger,
    SpiderQueen,
    BanditSpider,
    Orochi,
    TrueOrochi,
    Waka,
    Waka2,
    Blight,
    EvilRao,
    Oki,
    Nagi,
    Dogu,
    Ninetails,
    CanineWarriorChu,
    CanineWarriorJin,
    CanineWarriorGi,
    CanineWarriorTei,
    CanineWarriorChi,
    CanineWarriorKo,
    CanineWarriorRei,
    CanineWarriorShin,
    TubeFox,
    GoldenDemonLechku,
    SilverDemonNechku,
    YamiRed,
    YamiGreen,
    YamiBlue,
    YamiYellow,
    YamiHand,
    NUM_BESTIARY_ENTRIES
};

static const char *name[NUM_BESTIARY_ENTRIES] = {
    "Green Imp",
    "Red Imp",
    "Yellow Imp",
    "Blue Imp",
    "Black Imp",
    "Headless Guardian",
    "Bell Guardian",
    "Halo Guardian",
    "Executioner Guardian",
    "Namahage",
    "Blade Namahage",
    "Bucket Namahage",
    "Umbrella Namahage",
    "Cannon Namahage",
    "Clay Soldier",
    "Clay Samurai",
    "Clay Drummer",
    "Clay Flyer",
    "Clay Shogun",
    "Bud Ogre",
    "Chimera",
    "Igloo Turtle",
    "Dead Fish",
    "Crow Tengu",
    "Ubume",
    "Fire Eye",
    "Ice Mouth",
    "Thunder Ear",
    "Earth Nose",
    "Fire Doom Mirror",
    "Ice Doom Mirror",
    "Thunder Doom Mirror",
    "Wind Doom Mirror",
    "Poltergeist",
    "Ichiro",
    "Jiro",
    "Saburo",
    "Blue Cyclops",
    "Great Tengu",
    "Crimson Helm",
    "Red Ogre",
    "Blue Ogre",
    "Bull Charger",
    "Spider Queen",
    "Bandit Spider",
    "Orochi",
    "True Orochi",
    "Waka (w/ flute)",
    "Waka (w/ swords)",
    "Blight",
    "Evil Rao",
    "Oki",
    "Nagi",
    "Dogu",
    "Ninetails",
    "Canine Warrior Chu",
    "Canine Warrior Jin",
    "Canine Warrior Gi",
    "Canine Warrior Tei",
    "Canine Warrior Chi",
    "Canine Warrior Ko",
    "Canine Warrior Rei",
    "Canine Warrior Shin",
    "Tube Fox",
    "Golden Demon Lechku",
    "Silver Demon Nechku",
    "Yami (red)",
    "Yami (green)",
    "Yami (blue)",
    "Yami (yellow)",
    "Yami (hand)",
};

inline const char *GetName(unsigned index)
{
    if (index < NUM_BESTIARY_ENTRIES)
    {
        return name[index];
    }
    return "invalid";
}
} // namespace BestiaryTome
} // namespace okami
