#pragma once

// Source: https://okami.speedruns.wiki/Item_Table

namespace okami
{
namespace ItemTypes
{
enum Enum
{
    None,
    SpiritGlobeS,
    SpiritGlobeM,
    SpiritGlobeL,
    HolyBoneL,
    SunFragment,
    AstralPouch,
    InkBottle,
    ExorcismSlipL,
    ExorcismSlipM,
    ExorcismSlipS,
    PeaceBell,
    VengeanceSlip,
    InkfinityStone,
    MermaidCoin,
    GoldenPeach,
    DivineRetribution,
    SnarlingBeast,
    InfinityJudge,
    TrinityMirror,
    SolarFlare,
    DevoutBeads,
    LifeBeads,
    ExorcismBeads,
    ResurrectionBeads,
    TundraBeads,
    Tsumugari,
    SevenStrike,
    BladeOfKusanagi,
    EighthWonder,
    ThunderEdge,
    DemonFang,
    Peach,
    Apple,
    Orange,
    BakedOranges,
    Radish,
    Turnip,
    Ginseng,
    Cabbage,
    ChineseCabbage,
    CherryCake,
    Potato,
    Watermelon,
    BaleOfRice,
    RoastedMeat,
    BambooShoot,
    RoastedFish,
    RiceBalls,
    Dumplings,
    Grapes,
    Gourd,
    SasaRice,
    SasaFish,
    SasaEggRolls,
    SasaMeat,
    SasaCrab,
    SasaFruit,
    SasaDumplings,
    SasaHotchpotch,
    SasaCake,
    RiceStew,
    MilletDumplings,
    KamikiOrange,
    RuinsKey,
    OddlyShapedTurnip,
    CanineTracker,
    LuckyMallet,
    BorderKey,
    DragonOrb,
    FoxRods,
    ThunderBrew,
    ShellAmulet,
    Mask,
    OgreLiver,
    LipsOfIce,
    EyeballOfFire,
    BlackDemonHorn,
    LoyaltyOrb,
    JusticeOrb,
    DutyOrb,
    HourglassOrb,
    Unused_52,
    Yen10,
    Yen50,
    Yen100,
    Yen150,
    Yen500,
    Unused_58,
    Praise,
    Nothing,
    KarmicTransformer1,
    VistaOftheGods,
    ScrollLegendOfOrochi,
    ScrollMotherTree,
    GoldenMushroom,
    GimmickGear,
    ScrollNorthernLand,
    PurificationSake,
    Sewaprolo,
    ScrollCelestialEnvoy,
    ScrollTribeOftheMoon,
    ScrollPowerSlash3,
    ScrollCherryBomb2,
    ScrollCherrryBomb3,
    ScrollLandOftheGods,
    ScrollAnotherCivilization,
    ScrollBrushTips,
    ScrollTravelTips,
    ScrollBattleTips,
    ScrollDiggingTips,
    ScrollHolyArtifacts,
    TravelersCharm,
    Charcoal,
    BlindingSnow,
    TreasureBox,
    SpiritGlobeSInkPot,
    HerbalMedicine,
    Pinwheel,
    MarlinRod,
    Unused_78,
    KarmicTransformer3,
    KarmicTransformer8,
    KarmicTransformer7,
    KarmicTransformer9,
    ScrollInfernoTech,
    ScrollWaterspoutTech2,
    ScrollGalestormTech,
    ScrollThunderstormTech,
    ScrollPowerSlash2,
    Unused_82,
    Chestnut,
    ScrollEnhancingDivinity,
    ScrollFeeding,
    ScrollGodhoodTips,
    ScrollFleeingBattle,
    ScrollEnhancingWeapons,
    ScrollGreensproutTips,
    ScrollInkBulletTips,
    ScrollMarkOfKabegami,
    ScrollVeilOfMistTech,
    ScrollWaterspoutTech1,
    HolyBoneM,
    HolyBoneS,
    FeedbagMeat,
    FeedbagHerbs,
    FeedbagSeeds,
    FeedbagFish,
    Sashimi,
    GoldenLuckyCat,
    ThiefsGlove,
    WoodMat,
    GoldenInkPot,
    SteelFistSake,
    SteelSoulSake,
    GodlyCharm,
    WaterTablet,
    FireTablet,
    GoldDust,
    FogPot,
    WhitePorcelainPot,
    KutaniPottery,
    Unused_A2,
    IncenseBurner,
    Vase,
    SilverPocketWatch,
    RatStatue,
    BullHorn,
    Unused_A8,
    EtchedGlass,
    LacquerwareSet,
    WoodenBear,
    Unused_AC,
    GlassBeads,
    DragonflyBead,
    Unused_AF,
    CoralFragment,
    Crystal,
    Pearl,
    RubyTassels,
    BullStatue,
    TigerStatue,
    RabbitStatue,
    DragonStatue,
    SnakeStatue,
    HorseStatue,
    SheepStatue,
    MonkeyStatue,
    RoosterStatue,
    DogStatue,
    BoarStatue,
    CatStatue,
    SapphireTassels,
    EmeraldTassels,
    TurqoiseTassels,
    AgateTassels,
    AmberTassels,
    CatsEyeTassels,
    AmethystTassels,
    JadeTassels,
    KarmicReturner,
    KarmicTransformer2,
    KarmicTransformer6,
    KarmicTransformer5,
    StrayBead,
    StringOfBeads,
    GiantSalmon,
    KarmicTransformer4,
    SupremeTuna,
    MountainTrout,
    RedSnapper,
    StripedSnapper,
    Salmon,
    Koi,
    Huchen,
    Robalo,
    BlackBass,
    Clownfish,
    Bonito,
    Yellowtail,
    Sweetfish,
    Trout,
    Smelt,
    Killifish,
    FlyingFish,
    Sturgeon,
    Sunfish,
    FreshwaterEel,
    Loach,
    Moray,
    Oarfish,
    Monkfish,
    Catfish,
    GiantCatfish,
    Goby,
    Lobster,
    Crawfish,
    Scallop,
    Nautilus,
    Manta,
    Blowfish,
    RiverCrab,
    Starfish,
    Marlin,
    LoggerheadTurtle,
    SeaHorse,
    Octopus,
    Squid,
    TsutaRuinsMap,
    MoonCaveMap,
    ImperialPalaceMap,
    OniIslandMap,
    WawkuShrineMap,
    GaleShrineMap,
    Whopper,
    CutlassFish,
    NUM_ITEM_TYPES,

    ArchipelagoTestItem1 = Unused_78,
    ArchipelagoTestItem2 = Chestnut,
    ArchipelagoTestItem3 = Unused_82,
    ArchipelagoTestItem4 = Unused_A2,
    ArchipelagoTestItem5 = Unused_A8,
    ArchipelagoTestItem6 = Unused_AC,
    ArchipelagoTestItem7 = Unused_AF,
};

static const char *names[NUM_ITEM_TYPES] = {
    "None",
    "Spirit Globe S",
    "Spirit Globe M",
    "Spirit Globe L",
    "Holy Bone L",
    "Sun Fragment",
    "Astral Pouch",
    "Ink Bottle",
    "Exorcism Slip L",
    "Exorcism Slip M",
    "Exorcism Slip S",
    "Peace Bell",
    "Vengeance Slip",
    "Inkfinity Stone",
    "Mermaid Coin",
    "Golden Peach",
    "Divine Retribution",
    "Snarling Beast",
    "Infinity Judge",
    "Trinity Mirror",
    "Solar Flare",
    "Devout Beads",
    "Life Beads",
    "Exorcism Beads",
    "Resurrection Beads",
    "Tundra Beads",
    "Tsumugari",
    "Seven Strike",
    "Blade of Kusanagi",
    "Eighth Wonder",
    "Thunder Edge",
    "Demon Fang",
    "Peach",
    "Apple",
    "Orange",
    "Baked Oranges",
    "Radish",
    "Turnip",
    "Ginseng",
    "Cabbage",
    "Chinese Cabbage",
    "Cherry Cake",
    "Potato",
    "Watermelon",
    "Bale of Rice",
    "Roasted Meat",
    "Bamboo Shoot",
    "Roasted Fish",
    "Rice Balls",
    "Dumplings",
    "Grapes",
    "Gourd",
    "Sasa Rice",
    "Sasa Fish",
    "Sasa Egg Rolls",
    "Sasa Meat",
    "Sasa Crab",
    "Sasa Fruit",
    "Sasa Dumplings",
    "Sasa Hotchpotch",
    "Sasa Cake",
    "Rice Stew",
    "Millet Dumplings",
    "Kamiki Orange",
    "Ruins Key",
    "Oddly Shaped Turnip",
    "Canine Tracker",
    "Lucky Mallet",
    "Border Key",
    "Dragon Orb",
    "Fox Rods",
    "Thunder Brew",
    "Shell Amulet",
    "Mask",
    "Ogre Liver",
    "Lips of Ice",
    "Eyeball of Fire",
    "Black Demon Horn",
    "Loyalty Orb",
    "Justice Orb",
    "Duty Orb",
    "Hourglass Orb",
    "Unused52",
    "10 Yen",
    "50 Yen",
    "100 Yen",
    "150 Yen",
    "500 Yen",
    "Unused58",
    "Praise",
    "Nothing",
    "Karmic Transformer 1",
    "Vista of the Gods",
    "[Legend of Orochi]",
    "[Mother Tree]",
    "Golden Mushroom",
    "Gimmick Gear",
    "[Northern Land]",
    "8 Purification Sake",
    "Sewaprolo",
    "[Celestial Envoy]",
    "[Tribe of the Moon]",
    "[Power Slash 3]",
    "[Cherry Bomb 2]",
    "[Cherrry Bomb 3]",
    "[Land of the Gods]",
    "[Another Civilization]",
    "[Brush Tips]",
    "[Travel Tips]",
    "[Battle Tips]",
    "[Digging Tips]",
    "[Holy Artifacts]",
    "Traveler's Charm",
    "Charcoal",
    "Blinding Snow",
    "Treasure Box",
    "Spirit Globe S + Ink Bottle",
    "Herbal Medicine",
    "Pinwheel",
    "Marlin Rod",
    "Unused78",
    "Karmic Transformer 3",
    "Karmic Transformer 8",
    "Karmic Transformer 7",
    "Karmic Transformer 9",
    "[Inferno Tech]",
    "[Waterspout Tech 2]",
    "[Galestorm Tech]",
    "[Thunderstorm Tech]",
    "[Power Slash 2]",
    "Unused82",
    "Chestnut",
    "[Enhancing Divinity]",
    "[Feeding]",
    "[Godhood Tips]",
    "[Fleeing Battle]",
    "[Enhancing Weapons]",
    "[Greensprout Tips]",
    "[Ink Bullet Tips]",
    "[Mark of Kabegami]",
    "[Veil of Mist Tech]",
    "[Waterspout Tech 1]",
    "Holy Bone M",
    "Holy Bone S",
    "Feedbag (Meat)",
    "Feedbag (Herbs)",
    "Feedbag (Seeds)",
    "Feedbag (Fish)",
    "Sashimi",
    "Golden Lucky Cat",
    "Thief's Glove",
    "Wood Mat",
    "Golden Ink Pot",
    "Steel Fist Sake",
    "Steel Soul Sake",
    "Godly Charm",
    "Water Tablet",
    "Fire Tablet",
    "Gold Dust",
    "Fog Pot",
    "White Porcelain Pot",
    "Kutani Pottery",
    "UnusedA2",
    "Incense Burner",
    "Vase",
    "Silver Pocket Watch",
    "Rat Statue",
    "Bull Horn",
    "UnusedA8",
    "Etched Glass",
    "Lacquerware Set",
    "Wooden Bear",
    "UnusedAC",
    "Glass Beads",
    "Dragonfly Bead",
    "UnusedAF",
    "Coral Fragment",
    "Crystal",
    "Pearl",
    "Ruby Tassels",
    "Bull Statue",
    "Tiger Statue",
    "Rabbit Statue",
    "Dragon Statue",
    "Snake Statue",
    "Horse Statue",
    "Sheep Statue",
    "Monkey Statue",
    "Rooster Statue",
    "Dog Statue",
    "Boar Statue",
    "Cat Statue",
    "Sapphire Tassels",
    "Emerald Tassels",
    "Turqoise Tassels",
    "Agate Tassels",
    "Amber Tassels",
    "Cat's Eye Tassels",
    "Amethyst Tassels",
    "Jade Tassels",
    "Karmic Returner",
    "Karmic Transformer 2",
    "Karmic Transformer 6",
    "Karmic Transformer 5",
    "Stray Bead",
    "String of Beads",
    "Giant Salmon",
    "Karmic Transformer 4",
    "Supreme Tuna",
    "Mountain Trout",
    "Red Snapper",
    "Striped Snapper",
    "Salmon",
    "Koi",
    "Huchen",
    "Robalo",
    "Black Bass",
    "Clownfish",
    "Bonito",
    "Yellowtail",
    "Sweetfish",
    "Trout",
    "Smelt",
    "Killifish",
    "Flying Fish",
    "Sturgeon",
    "Sunfish",
    "Freshwater Eel",
    "Loach",
    "Moray",
    "Oarfish",
    "Monkfish",
    "Catfish",
    "Giant Catfish",
    "Goby",
    "Lobster",
    "Crawfish",
    "Scallop",
    "Nautilus",
    "Manta",
    "Blowfish",
    "River Crab",
    "Starfish",
    "Marlin",
    "Loggerhead Turtle",
    "Sea Horse",
    "Octopus",
    "Squid",
    "Tsuta Ruins Map",
    "Moon Cave Map",
    "Imperial Palace Map",
    "Oni Island Map",
    "Wawku Shrine Map",
    "Gale Shrine Map",
    "Whopper",
    "Cutlass Fish",
};

inline const char *GetName(unsigned value)
{
    if (value < NUM_ITEM_TYPES)
    {
        return names[value];
    }
    return "invalid";
}
} // namespace ItemTypes
} // namespace okami
