
#pragma once
#include <cstdint>
#include <string>
#include <unordered_map>

namespace okami
{
/// Current inventory item ID
constexpr uintptr_t inventoryItemID = 0x7A9814; // uint16_t

/// Current inventory string ID
constexpr uintptr_t inventoryStringID = 0x9C148E; // uint16_t

enum class ItemCategory
{
    Pickup,
    Consumable,
    Collectible,
    KeyItem,
    Weapon,
    Food,
    KT,
    TravelGuide,
    Artifact,
    Treasure,
    Fish,
    Map,
    HeldItem,
    Unused
};

struct ItemData
{
    std::string Name;
    ItemCategory Category;
};

inline static const std::unordered_map<uint16_t, ItemData> ItemTable = {{0x0001, {"Spirit Globe S", ItemCategory::Pickup}},
                                                                        {0x0002, {"Spirit Globe M", ItemCategory::Pickup}},
                                                                        {0x0003, {"Spirit Globe L", ItemCategory::Pickup}},
                                                                        {0x0004, {"Holy Bone L", ItemCategory::Consumable}},
                                                                        {0x0005, {"Sun Fragment", ItemCategory::Collectible}},
                                                                        {0x0006, {"Astral Pouch", ItemCategory::KeyItem}},
                                                                        {0x0007, {"Ink Bottle", ItemCategory::Pickup}},
                                                                        {0x0008, {"Exorcism Slip L", ItemCategory::Consumable}},
                                                                        {0x0009, {"Exorcism Slip M", ItemCategory::Consumable}},
                                                                        {0x000A, {"Exorcism Slip S", ItemCategory::Consumable}},
                                                                        {0x000B, {"Peace Bell", ItemCategory::Artifact}},
                                                                        {0x000C, {"Vengeance Slip", ItemCategory::Consumable}},
                                                                        {0x000D, {"Inkfinity Stone", ItemCategory::Consumable}},
                                                                        {0x000E, {"Mermaid Coin", ItemCategory::Consumable}},
                                                                        {0x000F, {"Golden Peach", ItemCategory::Consumable}},
                                                                        {0x0010, {"Divine Retribution", ItemCategory::Consumable}},
                                                                        {0x0011, {"Snarling Beast", ItemCategory::Weapon}},
                                                                        {0x0012, {"Infinity Judge", ItemCategory::Weapon}},
                                                                        {0x0013, {"Trinity Mirror", ItemCategory::Weapon}},
                                                                        {0x0014, {"Solar Flare", ItemCategory::Weapon}},
                                                                        {0x0015, {"Devout Beads", ItemCategory::Weapon}},
                                                                        {0x0016, {"Life Beads", ItemCategory::Weapon}},
                                                                        {0x0017, {"Exorcism Beads", ItemCategory::Weapon}},
                                                                        {0x0018, {"Resurrection Beads", ItemCategory::Weapon}},
                                                                        {0x0019, {"Tundra Beads", ItemCategory::Weapon}},
                                                                        {0x001A, {"Tsumugari", ItemCategory::Weapon}},
                                                                        {0x001B, {"Seven Strike", ItemCategory::Weapon}},
                                                                        {0x001C, {"Blade of Kusanagi", ItemCategory::Weapon}},
                                                                        {0x001D, {"Eighth Wonder", ItemCategory::Weapon}},
                                                                        {0x001E, {"Thunder Edge", ItemCategory::Weapon}},
                                                                        {0x001F, {"Demon Fang", ItemCategory::Collectible}},
                                                                        {0x0020, {"Peach", ItemCategory::Food}},
                                                                        {0x0021, {"Apple", ItemCategory::Food}},
                                                                        {0x0022, {"Orange", ItemCategory::Food}},
                                                                        {0x0023, {"Baked Oranges", ItemCategory::Food}},
                                                                        {0x0024, {"Radish", ItemCategory::Food}},
                                                                        {0x0025, {"Turnip", ItemCategory::Food}},
                                                                        {0x0026, {"Ginseng", ItemCategory::Food}},
                                                                        {0x0027, {"Cabbage", ItemCategory::Food}},
                                                                        {0x0028, {"Chinese Cabbage", ItemCategory::Food}},
                                                                        {0x0029, {"Cherry Cake", ItemCategory::Food}},
                                                                        {0x002A, {"Potato", ItemCategory::Food}},
                                                                        {0x002B, {"Watermelon", ItemCategory::Food}},
                                                                        {0x002C, {"Bale of Rice", ItemCategory::Food}},
                                                                        {0x002D, {"Roasted Meat", ItemCategory::Food}},
                                                                        {0x002E, {"Bamboo Shoot", ItemCategory::Food}},
                                                                        {0x002F, {"Roasted Fish", ItemCategory::Food}},
                                                                        {0x0030, {"Rice Balls", ItemCategory::Food}},
                                                                        {0x0031, {"Dumplings", ItemCategory::Food}},
                                                                        {0x0032, {"Grapes", ItemCategory::Food}},
                                                                        {0x0033, {"Gourd", ItemCategory::Food}},
                                                                        {0x0034, {"Sasa Rice", ItemCategory::Food}},
                                                                        {0x0035, {"Sasa Fish", ItemCategory::Food}},
                                                                        {0x0036, {"Sasa Egg Rolls", ItemCategory::Food}},
                                                                        {0x0037, {"Sasa Meat", ItemCategory::Food}},
                                                                        {0x0038, {"Sasa Crab", ItemCategory::Food}},
                                                                        {0x0039, {"Sasa Fruit", ItemCategory::Food}},
                                                                        {0x003A, {"Sasa Dumplings", ItemCategory::Food}},
                                                                        {0x003B, {"Sasa Hotchpotch", ItemCategory::Food}},
                                                                        {0x003C, {"Sasa Cake", ItemCategory::Food}},
                                                                        {0x003D, {"Rice Stew", ItemCategory::Food}},
                                                                        {0x003E, {"Millet Dumplings", ItemCategory::Food}},
                                                                        {0x003F, {"Kamiki Orange", ItemCategory::Food}},
                                                                        {0x0040, {"Ruins Key", ItemCategory::HeldItem}},
                                                                        {0x0041, {"Oddly Shaped Turnip", ItemCategory::HeldItem}},
                                                                        {0x0042, {"Canine Tracker", ItemCategory::KeyItem}},
                                                                        {0x0043, {"Lucky Mallet", ItemCategory::KeyItem}},
                                                                        {0x0044, {"Border Key", ItemCategory::KeyItem}},
                                                                        {0x0045, {"Dragon Orb", ItemCategory::KeyItem}},
                                                                        {0x0046, {"Fox Rods", ItemCategory::KeyItem}},
                                                                        {0x0047, {"Thunder Brew", ItemCategory::KeyItem}},
                                                                        {0x0048, {"Shell Amulet", ItemCategory::KeyItem}},
                                                                        {0x0049, {"Mask", ItemCategory::KeyItem}},
                                                                        {0x004A, {"Ogre Liver", ItemCategory::KeyItem}},
                                                                        {0x004B, {"Lips of Ice", ItemCategory::KeyItem}},
                                                                        {0x004C, {"Eyeball of Fire", ItemCategory::KeyItem}},
                                                                        {0x004D, {"Black Demon Horn", ItemCategory::KeyItem}},
                                                                        {0x004E, {"Loyalty Orb", ItemCategory::KeyItem}},
                                                                        {0x004F, {"Justice Orb", ItemCategory::KeyItem}},
                                                                        {0x0050, {"Duty Orb", ItemCategory::KeyItem}},
                                                                        {0x0051, {"Hourglass Orb", ItemCategory::Pickup}},
                                                                        {0x0053, {"10 Yen", ItemCategory::Pickup}},
                                                                        {0x0054, {"50 Yen", ItemCategory::Pickup}},
                                                                        {0x0055, {"100 Yen", ItemCategory::Pickup}},
                                                                        {0x0056, {"150 Yen", ItemCategory::Pickup}},
                                                                        {0x0057, {"500 Yen", ItemCategory::Pickup}},
                                                                        {0x0059, {"Praise", ItemCategory::Pickup}},
                                                                        {0x005A, {"Nothing", ItemCategory::Unused}},
                                                                        {0x005B, {"Karmic Transformer 1", ItemCategory::KT}},
                                                                        {0x005C, {"Vista of the Gods", ItemCategory::HeldItem}},
                                                                        {0x005D, {"Legend of Orochi", ItemCategory::TravelGuide}},
                                                                        {0x005E, {"Mother Tree", ItemCategory::TravelGuide}},
                                                                        {0x005F, {"Golden Mushroom", ItemCategory::KeyItem}},
                                                                        {0x0060, {"Gimmick Gear", ItemCategory::KeyItem}},
                                                                        {0x0061, {"Northern Land", ItemCategory::TravelGuide}},
                                                                        {0x0062, {"8 Purification Sake", ItemCategory::KeyItem}},
                                                                        {0x0063, {"Sewaprolo", ItemCategory::KeyItem}},
                                                                        {0x0064, {"Celestial Envoy", ItemCategory::TravelGuide}},
                                                                        {0x0065, {"Tribe of the Moon", ItemCategory::TravelGuide}},
                                                                        {0x0066, {"Power Slash 3", ItemCategory::TravelGuide}},
                                                                        {0x0067, {"Cherry Bomb 2", ItemCategory::TravelGuide}},
                                                                        {0x0068, {"Cherrry Bomb 3", ItemCategory::TravelGuide}},
                                                                        {0x0069, {"Land of the Gods", ItemCategory::TravelGuide}},
                                                                        {0x006A, {"Another Civilization", ItemCategory::TravelGuide}},
                                                                        {0x006B, {"Brush Tips", ItemCategory::TravelGuide}},
                                                                        {0x006C, {"Travel Tips", ItemCategory::TravelGuide}},
                                                                        {0x006D, {"Battle Tips", ItemCategory::TravelGuide}},
                                                                        {0x006E, {"Digging Tips", ItemCategory::TravelGuide}},
                                                                        {0x006F, {"Holy Artifacts", ItemCategory::TravelGuide}},
                                                                        {0x0070, {"Traveler's Charm", ItemCategory::Consumable}},
                                                                        {0x0071, {"Charcoal", ItemCategory::KeyItem}},
                                                                        {0x0072, {"Blinding Snow", ItemCategory::KeyItem}},
                                                                        {0x0073, {"Treasure Box", ItemCategory::KeyItem}},
                                                                        {0x0074, {"Spirit Globe S + Ink Pot", ItemCategory::Pickup}},
                                                                        {0x0075, {"Herbal Medicine", ItemCategory::KeyItem}},
                                                                        {0x0076, {"Pinwheel", ItemCategory::KeyItem}},
                                                                        {0x0077, {"Marlin Rod", ItemCategory::KeyItem}},
                                                                        {0x0079, {"Karmic Transformer 3", ItemCategory::KT}},
                                                                        {0x007A, {"Karmic Transformer 8", ItemCategory::KT}},
                                                                        {0x007B, {"Karmic Transformer 7", ItemCategory::KT}},
                                                                        {0x007C, {"Karmic Transformer 9", ItemCategory::KT}},
                                                                        {0x007D, {"Inferno Tech", ItemCategory::TravelGuide}},
                                                                        {0x007E, {"Waterspout Tech 2", ItemCategory::TravelGuide}},
                                                                        {0x007F, {"Galestorm Tech", ItemCategory::TravelGuide}},
                                                                        {0x0080, {"Thunderstorm Tech", ItemCategory::TravelGuide}},
                                                                        {0x0081, {"Power Slash 2", ItemCategory::TravelGuide}},
                                                                        {0x0083, {"Chestnut", ItemCategory::Unused}},
                                                                        {0x0084, {"Enhancing Divinity", ItemCategory::TravelGuide}},
                                                                        {0x0085, {"Feeding", ItemCategory::TravelGuide}},
                                                                        {0x0086, {"Godhood Tips", ItemCategory::TravelGuide}},
                                                                        {0x0087, {"Fleeing Battle", ItemCategory::TravelGuide}},
                                                                        {0x0088, {"Enhancing Weapons", ItemCategory::TravelGuide}},
                                                                        {0x0089, {"Greensprout Tips", ItemCategory::TravelGuide}},
                                                                        {0x008A, {"Ink Bullet Tips", ItemCategory::TravelGuide}},
                                                                        {0x008B, {"Mark of Kabegami", ItemCategory::TravelGuide}},
                                                                        {0x008C, {"Veil of Mist Tech", ItemCategory::TravelGuide}},
                                                                        {0x008D, {"Waterspout Tech 1", ItemCategory::TravelGuide}},
                                                                        {0x008E, {"Holy Bone M", ItemCategory::Consumable}},
                                                                        {0x008F, {"Holy Bone S", ItemCategory::Consumable}},
                                                                        {0x0090, {"Feedbag (Meat)", ItemCategory::Consumable}},
                                                                        {0x0091, {"Feedbag (Herbs)", ItemCategory::Consumable}},
                                                                        {0x0092, {"Feedbag (Seeds)", ItemCategory::Consumable}},
                                                                        {0x0093, {"Feedbag (Fish)", ItemCategory::Consumable}},
                                                                        {0x0094, {"Sashimi", ItemCategory::Food}},
                                                                        {0x0095, {"Golden Lucky Cat", ItemCategory::Artifact}},
                                                                        {0x0096, {"Thief's Glove", ItemCategory::Artifact}},
                                                                        {0x0097, {"Wood Mat", ItemCategory::Artifact}},
                                                                        {0x0098, {"Golden Ink Pot", ItemCategory::Artifact}},
                                                                        {0x0099, {"Steel Fist Sake", ItemCategory::Consumable}},
                                                                        {0x009A, {"Steel Soul Sake", ItemCategory::Consumable}},
                                                                        {0x009B, {"Godly Charm", ItemCategory::Consumable}},
                                                                        {0x009C, {"Water Tablet", ItemCategory::Artifact}},
                                                                        {0x009D, {"Fire Tablet", ItemCategory::Artifact}},
                                                                        {0x009E, {"Gold Dust", ItemCategory::Consumable}},
                                                                        {0x009F, {"Fog Pot", ItemCategory::KeyItem}},
                                                                        {0x00A0, {"White Porcelain Pot", ItemCategory::Treasure}},
                                                                        {0x00A1, {"Kutani Pottery", ItemCategory::Treasure}},
                                                                        {0x00A3, {"Incense Burner", ItemCategory::Treasure}},
                                                                        {0x00A4, {"Vase", ItemCategory::Treasure}},
                                                                        {0x00A5, {"Silver Pocket Watch", ItemCategory::Treasure}},
                                                                        {0x00A6, {"Rat Statue", ItemCategory::Treasure}},
                                                                        {0x00A7, {"Bull Horn", ItemCategory::Treasure}},
                                                                        {0x00A9, {"Etched Glass", ItemCategory::Treasure}},
                                                                        {0x00AA, {"Lacquerware Set", ItemCategory::Treasure}},
                                                                        {0x00AB, {"Wooden Bear", ItemCategory::Treasure}},
                                                                        {0x00AD, {"Glass Beads", ItemCategory::Treasure}},
                                                                        {0x00AE, {"Dragonfly Bead", ItemCategory::Treasure}},
                                                                        {0x00B0, {"Coral Fragment", ItemCategory::Treasure}},
                                                                        {0x00B1, {"Crystal", ItemCategory::Treasure}},
                                                                        {0x00B2, {"Pearl", ItemCategory::Treasure}},
                                                                        {0x00B3, {"Ruby Tassels", ItemCategory::Treasure}},
                                                                        {0x00B4, {"Bull Statue", ItemCategory::Treasure}},
                                                                        {0x00B5, {"Tiger Statue", ItemCategory::Treasure}},
                                                                        {0x00B6, {"Rabbit Statue", ItemCategory::Treasure}},
                                                                        {0x00B7, {"Dragon Statue", ItemCategory::Treasure}},
                                                                        {0x00B8, {"Snake Statue", ItemCategory::Treasure}},
                                                                        {0x00B9, {"Horse Statue", ItemCategory::Treasure}},
                                                                        {0x00BA, {"Sheep Statue", ItemCategory::Treasure}},
                                                                        {0x00BB, {"Monkey Statue", ItemCategory::Treasure}},
                                                                        {0x00BC, {"Rooster Statue", ItemCategory::Treasure}},
                                                                        {0x00BD, {"Dog Statue", ItemCategory::Treasure}},
                                                                        {0x00BE, {"Boar Statue", ItemCategory::Treasure}},
                                                                        {0x00BF, {"Cat Statue", ItemCategory::Treasure}},
                                                                        {0x00C0, {"Sapphire Tassels", ItemCategory::Treasure}},
                                                                        {0x00C1, {"Emerald Tassels", ItemCategory::Treasure}},
                                                                        {0x00C2, {"Turqoise Tassels", ItemCategory::Treasure}},
                                                                        {0x00C3, {"Agate Tassels", ItemCategory::Treasure}},
                                                                        {0x00C4, {"Amber Tassels", ItemCategory::Treasure}},
                                                                        {0x00C5, {"Cat's Eye Tassels", ItemCategory::Treasure}},
                                                                        {0x00C6, {"Amethyst Tassels", ItemCategory::Treasure}},
                                                                        {0x00C7, {"Jade Tassels", ItemCategory::Treasure}},
                                                                        {0x00C8, {"Karmic Returner", ItemCategory::KT}},
                                                                        {0x00C9, {"Karmic Transformer 2", ItemCategory::KT}},
                                                                        {0x00CA, {"Karmic Transformer 6", ItemCategory::KT}},
                                                                        {0x00CB, {"Karmic Transformer 5", ItemCategory::KT}},
                                                                        {0x00CC, {"Stray Bead", ItemCategory::Collectible}},
                                                                        {0x00CD, {"String of Beads", ItemCategory::Artifact}},
                                                                        {0x00CE, {"Giant Salmon", ItemCategory::Fish}},
                                                                        {0x00CF, {"Karmic Transformer 4", ItemCategory::KT}},
                                                                        {0x00D0, {"Supreme Tuna", ItemCategory::Fish}},
                                                                        {0x00D1, {"Mountain Trout", ItemCategory::Fish}},
                                                                        {0x00D2, {"Red Snapper", ItemCategory::Fish}},
                                                                        {0x00D3, {"Striped Snapper", ItemCategory::Fish}},
                                                                        {0x00D4, {"Salmon", ItemCategory::Fish}},
                                                                        {0x00D5, {"Koi", ItemCategory::Fish}},
                                                                        {0x00D6, {"Huchen", ItemCategory::Fish}},
                                                                        {0x00D7, {"Robalo", ItemCategory::Fish}},
                                                                        {0x00D8, {"Black Bass", ItemCategory::Fish}},
                                                                        {0x00D9, {"Clownfish", ItemCategory::Fish}},
                                                                        {0x00DA, {"Bonito", ItemCategory::Fish}},
                                                                        {0x00DB, {"Yellowtail", ItemCategory::Fish}},
                                                                        {0x00DC, {"Sweetfish", ItemCategory::Fish}},
                                                                        {0x00DD, {"Trout", ItemCategory::Fish}},
                                                                        {0x00DE, {"Smelt", ItemCategory::Fish}},
                                                                        {0x00DF, {"Killifish", ItemCategory::Fish}},
                                                                        {0x00E0, {"Flying Fish", ItemCategory::Fish}},
                                                                        {0x00E1, {"Sturgeon", ItemCategory::Fish}},
                                                                        {0x00E2, {"Sunfish", ItemCategory::Fish}},
                                                                        {0x00E3, {"Freshwater Eel", ItemCategory::Fish}},
                                                                        {0x00E4, {"Loach", ItemCategory::Fish}},
                                                                        {0x00E5, {"Moray", ItemCategory::Fish}},
                                                                        {0x00E6, {"Oarfish", ItemCategory::Fish}},
                                                                        {0x00E7, {"Monkfish", ItemCategory::Fish}},
                                                                        {0x00E8, {"Catfish", ItemCategory::Fish}},
                                                                        {0x00E9, {"Giant Catfish", ItemCategory::Fish}},
                                                                        {0x00EA, {"Goby", ItemCategory::Fish}},
                                                                        {0x00EB, {"Lobster", ItemCategory::Fish}},
                                                                        {0x00EC, {"Crawfish", ItemCategory::Fish}},
                                                                        {0x00ED, {"Scallop", ItemCategory::Fish}},
                                                                        {0x00EE, {"Nautilus", ItemCategory::Fish}},
                                                                        {0x00EF, {"Manta", ItemCategory::Fish}},
                                                                        {0x00F0, {"Blowfish", ItemCategory::Fish}},
                                                                        {0x00F1, {"River Crab", ItemCategory::Fish}},
                                                                        {0x00F2, {"Starfish", ItemCategory::Fish}},
                                                                        {0x00F3, {"Marlin", ItemCategory::Fish}},
                                                                        {0x00F4, {"Loggerhead Turtle", ItemCategory::Fish}},
                                                                        {0x00F5, {"Sea Horse", ItemCategory::Fish}},
                                                                        {0x00F6, {"Octopus", ItemCategory::Fish}},
                                                                        {0x00F7, {"Squid", ItemCategory::Fish}},
                                                                        {0x00F8, {"Tsuta Ruins Map", ItemCategory::Map}},
                                                                        {0x00F9, {"Moon Cave Map", ItemCategory::Map}},
                                                                        {0x00FA, {"Imperial Palace Map", ItemCategory::Map}},
                                                                        {0x00FB, {"Oni Island Map", ItemCategory::Map}},
                                                                        {0x00FC, {"Wawku Shrine Map", ItemCategory::Map}},
                                                                        {0x00FD, {"Gale Shrine Map", ItemCategory::Map}},
                                                                        {0x00FE, {"Whopper", ItemCategory::Fish}},
                                                                        {0x00FF, {"Cutlass Fish", ItemCategory::Fish}}};
} // namespace okami
