#pragma once

namespace okami
{
/**
 * @brief Enum representing all stray beads.
 */
namespace StrayBeads
{
enum Enum
{
    CaveOfNagi1,
    KamikiVillage1,
    KamikiVillage2,
    KamikiVillage3,
    ShinshuField1,
    ShinshuField2,
    ShinshuField3,
    ShinshuField4,
    ShinshuField5,
    ShinshuField6,
    HanaValley1,
    AgataForest1,
    AgataForest2,
    AgataForest3,
    AgataForest4,
    AgataForest5,
    AgataForest6,
    TsutaRuins1,
    TsutaRuins2,
    TsutaRuins3,
    TakaPass1,
    TakaPass2,
    TakaPass3,
    TakaPass4,
    TakaPass5,
    TakaPass6,
    KusaVillage1,
    KusaVillage2,
    KusaVillage3,
    SasaSanctuary1,
    SasaSanctuary2,
    SasaSanctuary3,
    GaleShrine1,
    GaleShrine2,
    GaleShrine3,
    CityCheckpoint1,
    CityCheckpoint2,
    CityCheckpoint3,
    CityCheckpoint4,
    CityCheckpoint5,
    RyoshimaCoast1,
    RyoshimaCoast2,
    RyoshimaCoast3,
    RyoshimaCoast4,
    RyoshimaCoast5,
    SeianCQtr1,
    SeianCQtr2,
    SeianCQtr3,
    SeianCQtr4,
    SeianCQtr5,
    SeianAQtr1,
    SeianAQtr2,
    SeianAQtr3,
    SeianAQtr4,
    SeianAQtr5,
    SeianAQtr6,
    SunkenShip1,
    SunkenShip2,
    ImperialPalace1,
    NRyoshimaCoast1,
    NRyoshimaCoast2,
    NRyoshimaCoast3,
    NRyoshimaCoast4,
    NRyoshimaCoast5,
    NRyoshimaCoast6,
    NRyoshimaCoast7,
    CatcallTower1,
    CatcallTower2,
    CatcallTower3,
    DragonPalace1,
    DragonPalace2,
    DragonPalace3,
    DragonPalace4,
    Kamui1,
    Kamui2,
    Kamui3,
    Kamui4,
    Kamui5,
    Kamui6,
    Wepkeer1,
    Wepkeer2,
    Wepkeer3,
    Wepkeer4,
    KamuaEzofuji1,
    KamuaEzofuji2,
    KamuaEzofuji3,
    KamuaEzofuji4,
    Yoshpet1,
    Yoshpet2,
    Yoshpet3,
    Ponctan1,
    Ponctan2,
    Ponctan3,
    InnerYoshpet1,
    InnerYoshpet2,
    InnerYoshpet3,
    WawkuShrine1,
    WawkuShrine2,
    WawkuShrine3,
    ArkOfYamato1,
    NUM_STRAY_BEADS
};
static const char *names[NUM_STRAY_BEADS] = {
    "Cave Of Nagi 1",    "Kamiki Village 1",  "Kamiki Village 2",  "Kamiki Village 3",  "Shinshu Field 1",   "Shinshu Field 2",   "Shinshu Field 3",
    "Shinshu Field 4",   "Shinshu Field 5",   "Shinshu Field 6",   "Hana Valley 1",     "Agata Forest 1",    "Agata Forest 2",    "Agata Forest 3",
    "Agata Forest 4",    "Agata Forest 5",    "Agata Forest 6",    "Tsuta Ruins 1",     "Tsuta Ruins 2",     "Tsuta Ruins 3",     "Taka Pass 1",
    "Taka Pass 2",       "Taka Pass 3",       "Taka Pass 4",       "Taka Pass 5",       "Taka Pass 6",       "Kusa Village 1",    "Kusa Village 2",
    "Kusa Village 3",    "Sasa Sanctuary 1",  "Sasa Sanctuary 2",  "Sasa Sanctuary 3",  "Gale Shrine 1",     "Gale Shrine 2",     "Gale Shrine 3",
    "City Checkpoint 1", "City Checkpoint 2", "City Checkpoint 3", "City Checkpoint 4", "City Checkpoint 5", "Ryoshima Coast 1",  "Ryoshima Coast 2",
    "Ryoshima Coast 3",  "Ryoshima Coast 4",  "Ryoshima Coast 5",  "Seian C. Qtr. 1",   "Seian C. Qtr. 2",   "Seian C. Qtr. 3",   "Seian C. Qtr. 4",
    "Seian C. Qtr. 5",   "Seian A. Qtr. 1",   "Seian A. Qtr. 2",   "Seian A. Qtr. 3",   "Seian A. Qtr. 4",   "Seian A. Qtr. 5",   "Seian A. Qtr. 6",
    "Sunken Ship 1",     "Sunken Ship 2",     "Imperial Palace 1", "NRyoshima Coast 1", "NRyoshima Coast 2", "NRyoshima Coast 3", "NRyoshima Coast 4",
    "NRyoshima Coast 5", "NRyoshima Coast 6", "NRyoshima Coast 7", "Catcall Tower 1",   "Catcall Tower 2",   "Catcall Tower 3",   "Dragon Palace 1",
    "Dragon Palace 2",   "Dragon Palace 3",   "Dragon Palace 4",   "Kamui 1",           "Kamui 2",           "Kamui 3",           "Kamui 4",
    "Kamui 5",           "Kamui 6",           "Wepkeer 1",         "Wepkeer 2",         "Wepkeer 3",         "Wepkeer 4",         "Kamua Ezofuji 1",
    "Kamua Ezofuji 2",   "Kamua Ezofuji 3",   "Kamua Ezofuji 4",   "Yoshpet 1",         "Yoshpet 2",         "Yoshpet 3",         "Ponctan 1",
    "Ponctan 2",         "Ponctan 3",         "Inner Yoshpet 1",   "Inner Yoshpet 2",   "Inner Yoshpet 3",   "Wawku Shrine 1",    "Wawku Shrine 2",
    "Wawku Shrine 3",    "Ark Of Yamato 1",
};

inline const char *GetName(unsigned value)
{
    if (value < NUM_STRAY_BEADS)
    {
        return names[value];
    }
    return "invalid";
}
} // namespace StrayBeads
} // namespace okami
